title: My Site
secret_key: 'PLEASE_CHANGE_THIS_NOT_SECURE'
database_uri: 'sqlite:///site_development.sqlite3'
home_page: 'posts#index'
nav_links:
  - name: About
    link: '/about'
  - name: Contact
    link: '/contact'
