"""Add publishing to posts

Revision ID: fa4484177bbf
Revises: ab5f112fc655
Create Date: 2018-05-04 14:47:53.735317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4484177bbf'
down_revision = 'ab5f112fc655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    op.drop_column('posts', 'published_at')
    # ### end Alembic commands ###
